import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, Clipboard, Clock3, ExternalLink, Link2, LogOut, Plus, RefreshCw, Search, Settings, Trash2, UserRound, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Logo from '../components/Logo';
import Toast from '../components/Toast';
import { api, shortUrl } from '../lib/api';
import { clearUser, getUser } from '../lib/auth';

const durations = [['1 hour', 60 * 60 * 1000], ['1 day', 24 * 60 * 60 * 1000], ['7 days', 7 * 24 * 60 * 60 * 1000], ['30 days', 30 * 24 * 60 * 60 * 1000]];
function formatDate(value) { if (!value) return '—'; return new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }); }
function relativeExpiry(value) { const ms = new Date(value) - Date.now(); if (ms <= 0) return 'Expired'; const d = Math.floor(ms / 86400000), h = Math.floor(ms / 3600000); if (d) return `${d}d left`; return `${h}h left`; }

export default function Dashboard() {
    const nav = useNavigate(); const user = getUser(); const [urls, setUrls] = useState([]); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [query, setQuery] = useState(''); const [form, setForm] = useState({ originalURL: '', expirationDuration: String(durations[1][1]) }); const [toast, setToast] = useState(null); const [showDelete, setShowDelete] = useState(false); const [deleteForm, setDeleteForm] = useState({ email: user?.email || '', password: '' });
    async function load() { setLoading(true); try { const d = await api('/user/urls'); setUrls(Array.isArray(d) ? d : []); } catch (err) { if (err.status === 401 || err.status === 403) { clearUser(); nav('/login'); } else setToast({ message: err.message, type: 'error' }); } finally { setLoading(false) } }
    useEffect(() => { load() }, []);
    async function create(e) { e.preventDefault(); if (!/^https?:\/\//i.test(form.originalURL.trim())) return setToast({ message: 'Enter a valid URL beginning with http:// or https://', type: 'error' }); setCreating(true); try { const d = await api('/url', { method: 'POST', body: JSON.stringify({ originalURL: form.originalURL.trim(), expirationDuration: Number(form.expirationDuration) }) }); setUrls(x => [d.data, ...x]); setForm({ ...form, originalURL: '' }); setToast({ message: 'Short URL created successfully.', type: 'success' }); } catch (err) { setToast({ message: err.message, type: 'error' }); } finally { setCreating(false) } }
    async function remove(slug) { try { await api(`/url/${encodeURIComponent(slug)}`, { method: 'DELETE' }); setUrls(x => x.filter(u => u.slug !== slug)); setToast({ message: 'Short link deleted.', type: 'success' }); } catch (err) { setToast({ message: err.message, type: 'error' }) } }
    async function logout() { try { await api('/auth/logout', { method: 'POST' }); } catch { } clearUser(); nav('/login') }
    async function deleteAccount(e) { e.preventDefault(); try { await api('/auth/delete-user', { method: 'DELETE', body: JSON.stringify(deleteForm) }); clearUser(); nav('/'); } catch (err) { setToast({ message: err.message, type: 'error' }); } }
    const filtered = useMemo(() => urls.filter(u => `${u.originalURL} ${u.slug} ${u.status}`.toLowerCase().includes(query.toLowerCase())), [urls, query]);
    return <div className="app-shell"><aside className="sidebar"><Logo /><div className="side-section"><span className="side-label">WORKSPACE</span><div className="side-link active"><Link2 size={17} /> My links</div><div className="side-link"><Settings size={17} /> Account</div></div><div className="side-bottom"><div className="mini-user"><div className="avatar">{user?.name?.slice(0, 1).toUpperCase() || 'U'}</div><div><strong>{user?.name || 'User'}</strong><span>{user?.email}</span></div></div><button className="side-logout" onClick={logout}><LogOut size={16} /> Log out</button></div></aside>
        <main className="dashboard"><header className="dash-header"><div><div className="eyebrow">YOUR WORKSPACE</div><h1>Good to see you, {user?.name?.split(' ')[0] || 'there'}.</h1><p>Manage every short link from one place.</p></div><div className="header-actions"><button className="icon-button" onClick={load} title="Refresh"><RefreshCw size={18} /></button><button className="user-chip"><UserRound size={16} /><span>{user?.email}</span></button></div></header>
            <section className="create-card"><div className="create-copy"><div className="create-icon"><Plus size={22} /></div><div><h2>Create a short link</h2><p>Paste a long URL and choose how long it should stay active.</p></div></div><form className="create-form" onSubmit={create}><div className="url-input"><Link2 size={18} /><input type="url" placeholder="https://example.com/your-long-url" value={form.originalURL} onChange={e => setForm({ ...form, originalURL: e.target.value })} required /></div><select value={form.expirationDuration} onChange={e => setForm({ ...form, expirationDuration: e.target.value })}>{durations.map(([label, val]) => <option key={val} value={val}>{label}</option>)}</select><button className="button primary" disabled={creating}>{creating ? 'Creating…' : <>Shorten <Plus size={17} /></>}</button></form></section>
            <div className="stats"><Stat label="Total links" value={urls.length} /><Stat label="Active" value={urls.filter(u => u.status === 'active' && new Date(u.expiresAt) > new Date()).length} /><Stat label="Expired" value={urls.filter(u => u.status === 'expired' || new Date(u.expiresAt) <= new Date()).length} /></div>
            <section className="links-section"><div className="links-toolbar"><div><h2>Your links</h2><p>{urls.length} link{urls.length === 1 ? '' : 's'} in your workspace</p></div><div className="search"><Search size={17} /><input placeholder="Search links…" value={query} onChange={e => setQuery(e.target.value)} /></div></div>{loading ? <div className="empty"><RefreshCw className="spin" /><p>Loading your links…</p></div> : filtered.length === 0 ? <div className="empty"><Link2 size={30} /><h3>{urls.length ? 'No matching links' : 'No short links yet'}</h3><p>{urls.length ? 'Try another search.' : 'Create your first short link above.'}</p></div> : <div className="link-list">{filtered.map(u => <LinkRow key={u._id || u.slug} item={u} onDelete={() => remove(u.slug)} onToast={setToast} />)}</div>}</section>
            <section className="danger-zone"><div><div className="danger-title"><AlertTriangle size={17} /> Danger zone</div><p>Deleting your account permanently removes your account and its access to your links.</p></div><button className="button danger" onClick={() => setShowDelete(true)}>Delete account</button></section>
        </main>{showDelete && <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={() => setShowDelete(false)}><X /></button><div className="danger-icon"><Trash2 /></div><h2>Delete your account?</h2><p>This action cannot be undone. Confirm your email and password to continue.</p><form className="form" onSubmit={deleteAccount}><label className="field"><span>Email</span><input type="email" value={deleteForm.email} onChange={e => setDeleteForm({ ...deleteForm, email: e.target.value })} required /></label><label className="field"><span>Password</span><input type="password" value={deleteForm.password} onChange={e => setDeleteForm({ ...deleteForm, password: e.target.value })} required /></label><button className="button danger full">Permanently delete account</button></form></div></div>}<Toast toast={toast} onClose={() => setToast(null)} /></div>
}
function Stat({ label, value }) { return <div className="stat"><span>{label}</span><strong>{value}</strong></div> }
function LinkRow({ item, onDelete, onToast }) { const link = shortUrl(item.slug); const active = item.status === 'active' && new Date(item.expiresAt) > new Date(); async function copy() { try { await navigator.clipboard.writeText(link); onToast({ message: 'Short URL copied to clipboard.', type: 'success' }); } catch { onToast({ message: link, type: 'success' }); } } return <article className="link-row"><div className="link-main"><div className="slug"><span className={`status-dot ${active ? 'active' : 'inactive'}`} /><strong>{link.replace(/^https?:\/\//, '')}</strong></div><a href={item.originalURL} target="_blank" rel="noreferrer" className="original">{item.originalURL}</a></div><div className="link-meta"><span className={`status ${active ? 'active' : 'inactive'}`}>{item.status}</span><span className="expiry"><Clock3 size={14} />{relativeExpiry(item.expiresAt)} · {formatDate(item.expiresAt)}</span></div><div className="row-actions"><button onClick={copy} title="Copy"><Clipboard size={16} /></button><a href={link} target="_blank" rel="noreferrer" title="Open"><ExternalLink size={16} /></a><button className="delete-btn" onClick={onDelete} title="Delete"><Trash2 size={16} /></button></div></article> }
