import { ArrowRight, Check, Clock3, Copy, Link2, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import Logo from '../components/Logo';
import { getUser } from '../lib/auth';

export default function Landing() {
 const user=getUser();
 return <div className="landing"><nav className="nav container"><Logo/><div className="nav-links"><a href="#features">Features</a><a href="#how">How it works</a>{user?<Link className="nav-cta" to="/dashboard">Dashboard <ArrowRight size={16}/></Link>:<><Link to="/login">Log in</Link><Link className="nav-cta" to="/register">Get started <ArrowRight size={16}/></Link></>}</div></nav>
 <main><section className="hero container"><div className="hero-copy"><div className="pill"><Sparkles size={14}/> Fast. Private. Yours.</div><h1>Turn long links into <span>short stories.</span></h1><p>Shorten, organize and share your links from one clean dashboard. Built around your existing Node.js API and cookie-based authentication.</p><div className="hero-actions"><Link className="button primary" to={user?'/dashboard':'/register'}>{user?'Open dashboard':'Start shortening'} <ArrowRight size={17}/></Link><a className="button ghost" href="#how">See how it works</a></div><div className="trust-row"><span><ShieldCheck size={15}/> HTTP-only auth cookies</span><span><Zap size={15}/> Instant redirects</span></div></div><div className="hero-demo"><div className="demo-window"><div className="window-bar"><span/><span/><span/><b>shortly / dashboard</b></div><div className="demo-body"><div className="demo-stat"><span>Total links</span><strong>24</strong></div><div className="demo-stat"><span>Active</span><strong>21</strong></div><div className="demo-input"><span>https://example.com/very-long-product-url...</span><button><Link2 size={17}/></button></div><div className="demo-link"><span>short.ly/a8Kp2qL</span><span className="live"><i/> active</span></div><div className="demo-link"><span>short.ly/zP4m1Tx</span><span className="live"><i/> active</span></div></div></div></div></section>
 <section id="features" className="section container"><div className="section-heading"><div className="eyebrow">WHY SHORTLY</div><h2>Everything you need. Nothing you don't.</h2><p>A focused interface for the API you've already built.</p></div><div className="feature-grid"><Feature icon={<Zap/>} title="Quick shortening" text="Generate a unique 7-character slug with a single request."/><Feature icon={<ShieldCheck/>} title="Private dashboard" text="JWT authentication lives in an HTTP-only cookie, keeping tokens out of your UI code."/><Feature icon={<Clock3/>} title="Expiring links" text="Choose how long a link should remain active when you create it."/><Feature icon={<Copy/>} title="One-click copy" text="Copy generated short URLs instantly and share them anywhere."/></div></section>
 <section id="how" className="section how container"><div className="section-heading"><div className="eyebrow">HOW IT WORKS</div><h2>Three steps. One shorter URL.</h2></div><div className="steps"><Step n="01" title="Create an account" text="Register, verify your email and sign in."/><Step n="02" title="Paste your URL" text="Choose an expiration duration and create the short link."/><Step n="03" title="Share it" text="Copy the generated link. Your API handles the redirect."/></div></section></main>
 <footer className="footer container"><Logo/><span>Built for a clean backend-first workflow.</span></footer></div>
}
function Feature({icon,title,text}){return <article className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>}
function Step({n,title,text}){return <div className="step"><div className="step-num">{n}</div><div><h3>{title}</h3><p>{text}</p></div><Check className="step-check" size={20}/></div>}
